### ISSUE TITLE
Purpose of project

### ISSUE THREAD

**Issue by iandees** [osmlab/osm-landmarks#4]
Can you add a stronger indication of what this list of landmarks is for to the readme? My assumption is that the landmarks are used to flag changesets that make changes to these objects, but it's not clear.

**Comment by geohacker** [comment]
@iandees - that's correct. The idea is to come up with a list of features in OSM that do not anticipate change often, or that are popular that if someone accidentally changes might break the map visually or otherwise. 

There'll be more notes in the readme soon, and utilities and scripts that are used to match a list of things to OSM features.
